### PR TITLE
13.0 fix search counts

### PR DESCRIPTION
**Pull request by ntsirintanis**
tmp, for migrating Danny's fix to 13.0

### CODE REVIEW

**Comment by ntsirintanis** [comment]
@ddejong-therp please take a look on this one. I'll test it asap

**Comment by thomaspaulb** [comment]
@ntsirintanis 

- Is this a back/forward port of another fix? If so, which?
- The connotation "tmp" feels to me like you're not really intending for this to be merged into OCB. If that's the case, could you rather open the PR targeting `sunflowerit/13.0` or `therpbv/13.0` instead of OCB itself? That way @ddejong-therp can review, but the OCA is not involved.

**Comment by ntsirintanis** [comment]
@thomaspaulb this already points to [sunflowerit/OCB](https://github.com/sunflowerit/OCB). So OCA is not involved. Further, I forwardported [this](https://github.com/OCA/OCB/pull/1045) in order to see if this resolves a specific issue, but unfortunately it does not.

**Comment by thomaspaulb** [comment]
@ntsirintanis Ah sorry, not sure how I thought it pointed to OCA.

**Comment by ntsirintanis** [comment]
> @ntsirintanis Ah sorry, not sure how I thought it pointed to OCA.

No worries, I am closing this one anyway

**Pull request closed without merging**
